import { defineSchema, defineTable } from 'convex/server';
import { v } from 'convex/values';

export default defineSchema({
  tours: defineTable({
    slug: v.string(),
    name: v.string(),
    tagline: v.string(),
    description: v.string(),
    longDescription: v.string(),
    duration: v.string(),
    durationMinutes: v.number(),
    price: v.number(),
    maxGuests: v.number(),
    imageUrl: v.string(),
    category: v.string(),
    highlights: v.array(v.string()),
    startTimes: v.array(v.string()),
    meetingPoint: v.string(),
    updatedAt: v.number(),
  }),

  bookings: defineTable({
    cancelled: v.union(v.number(), v.null()),
    date: v.string(),
    time: v.string(),
    guests: v.number(),
    bookerName: v.string(),
    bookerEmail: v.string(),
    tourId: v.id('tours'),
    checkoutAttemptId: v.optional(v.id('checkoutAttempts')),
    accessTokenHash: v.optional(v.string()),
    stripePaymentIntentId: v.optional(v.string()),
    paymentStatus: v.optional(v.literal('paid')),
    updatedAt: v.number(),
  }),

  checkoutAttempts: defineTable({
    tourId: v.id('tours'),
    date: v.string(),
    time: v.string(),
    guests: v.number(),
    bookerName: v.string(),
    bookerEmail: v.string(),
    unitPrice: v.number(),
    total: v.number(),
    currency: v.string(),
    stripeCheckoutSessionId: v.union(v.string(), v.null()),
    paymentStatus: v.union(
      v.literal('pending'),
      v.literal('paid'),
      v.literal('expired'),
      v.literal('failed'),
      v.literal('refund_pending'),
      v.literal('refunded'),
      v.literal('refund_failed'),
    ),
    expiresAt: v.number(),
    accessTokenHash: v.string(),
    failureReason: v.optional(v.literal('capacity_unavailable')),
    stripeRefundId: v.optional(v.string()),
    updatedAt: v.number(),
  }),
});
